### ISSUE TITLE
在编译成功后运行代码出错

### ISSUE THREAD

**Issue by zouzehua** [MingshanHe/Compliant-Control-and-Application#11]
ros版本：neotic
![2022-08-05 22-18-06 的屏幕截图](https://user-images.githubusercontent.com/72058400/183096436-b92a6d51-7923-433a-baca-fe08c0aff9ba.png)

运行launch文件报错

**Comment by MingshanHe** [comment]
请问运行的是那一段命令，遇到的这个错误。

**Comment by MingshanHe** [comment]
经过编译与调试仍未出现您这种情况，希望您能够提供更细节的操作，方便我复现这个错误。

**Comment by zouzehua** [comment]
> 经过编译与调试仍未出现您这种情况，希望您能够提供更细节的操作，方便我复现这个错

**Comment by zouzehua** [comment]
您好，我就是在运行roslaunch ur_gazebo ur5e_bringup.launch transmission_hw_interface:=hardware_interface/PositionJointInterface specified_controller:=cartesian_velocity_controller这个命令出现的错误，其他几个加载gazebo的命令也是出现相同的错误

**Comment by zouzehua** [comment]
您好，本来最开始我git下来整个包编译不通过
![2022-08-06 09-03-13 的屏幕截图](https://user-images.githubuserconte
![2022-08-06 09-03-27 的屏幕截图](https://user-images.githubusercontent.com/72058400/183227527-50c12cad-aa15-4397-827b-c38b33f422a4.png)
nt.com/72058400/183227521-09edf1db-6922-495a-a738-91e4e8b4176b.png)
我就试着把control_algorithms里面的impedance文件夹删了，结果编译成功，然后我运行其他控制代码加载gazebo都会报错，模型可以加载出来，
roslaunch ur_gazebo ur5e_bringup.launch transmission_hw_interface:=hardware_interface/PositionJointInterface specified_controller:=cartesian_velocity_controller
roslaunch mir_gazebo mir_empty_world.launch
roslaunch ur_gazebo ur5e_bringup.launch transmission_hw_interface:=hardware_interface/PositionJointInterface specified_controller:=cartesian_velocity_controller environment:=polish
![2022-08-06 09-14-46 的屏幕截图](https://user-images.githubusercontent.com/72058400/183227865-458036d5-b295-4ae0-a318-0f300c70e029.png)

**Comment by MingshanHe** [comment]
`   line 79 in ur_description/urdf/inc/ur_macro.xacro`
`
    <link name="${prefix}base_link"/>
    <link name="${prefix}base_link_inertia">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="${base_visual_mesh}"/>
        </geometry>
        <material name="${base_visual_material_name}">
          <color rgba="${base_visual_material_color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="${base_collision_mesh}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="${base_inertia_radius}" length="${base_inertia_length}" mass="${base_mass}">
        <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>
`
`   line 223 in ur_description/urdf/inc/ur_macro.xacro`
`
    <joint name="${prefix}base_link-base_link_inertia" type="fixed">
      <parent link="${prefix}base_link" />
      <child link="${prefix}base_link_inertia" />`
`
Please check this file in this project.
I think you have installed another ur_description with `apt`, so the solution may remove them (official ur_description package).

**Comment by zouzehua** [comment]
I checked the urdf file in ur_description, the code is the same as yours.  My entire code is downloaded from your repository.  I don't know if it is a problem with the ros version
![2022-08-06 21-55-48 的屏幕截图](https://user-images.githubusercontent.com/72058400/183252075-9e74bb26-f2fc-48a7-b329-87827fb5eead.png)
![2022-08-06 21-56-09 的屏幕截图](https://user-images.githubusercontent.com/72058400/183252081-65897cf2-0ebb-4a3a-bb8a-ec325278a237.png)

**Comment by MingshanHe** [comment]
@zouzehua  I still don't understand why this works in the CI (including the impedance package) and does not for you. My code has been tested in the `noetic` version, so it is not the main problem with your error. I think you could try to remove the ur_description package and install the official package with `apt`, like `sudo apt-get install ros-noetic-ur-description`.

**Comment by zouzehua** [comment]
I solved it by reinstalling the ubuntu

**Comment by ZZWang21** [comment]
Hi @zouzehua  which devel did you git? noetic or sim-devel? Thanks.
