### ISSUE TITLE
Some problems regarding /wrench

### ISSUE THREAD

**Issue by YuHoChau** [MingshanHe/Compliant-Control-and-Application#15]
你好：

感谢回复，在浏览了源码及尝试了`sim-devel`和`noetic`两个branch后依然有以下几个问题想请教，希望您能有空答复：
在`sim-devel` branch下，似乎`xacro`文件中的`六轴力传感器`和`/WrenchSigbakGenerate`都会通过消息`/wrench`发送到`/Admittance`。在不launch`ur5e.launch`的情况下，单独发布话题`/WrenchSignalGenerate`能够正确生成`fake wrench`，如下图：

<img width="1132" alt="Capture3" src="https://user-images.githubusercontent.com/63508270/197142133-31ab95fb-01a8-4b94-b10a-4627e9de6453.PNG">

然而，如果launch`ur5e.launch`及`/WrenchSignalGenerate`，（由于`ft_sensor`的干扰？）`/wrench`会产生巨大的震荡，如下图：

<img width="1071" alt="Capture4" src="https://user-images.githubusercontent.com/63508270/197142519-b55bd687-e90f-4169-810d-49d191477bd2.PNG">

下图是`sim-devel`branch下的Node Graph（`/wrench`有震荡）:

<img width="904" alt="Capture1" src="https://user-images.githubusercontent.com/63508270/197144464-e600131b-bb92-48f8-b957-7f6053d51e98.PNG">

以上是`sim-devel` branch的问题，同样我也尝试了`noetic`branch。`/wrench/force`和`/wrench/torque`依然有一个微小变化的值，`/wrench_fake`能够通过`/WrenchSigbakGenerate`正常发布但是无法发送到`/Admittance`，如下图：

<img width="919" alt="Capture2" src="https://user-images.githubusercontent.com/63508270/197144585-747afc14-0bc7-448d-acee-9d6ef2b313d1.PNG">

因此，我的疑惑是：
1) `ft_sensor`的作用？以及为何会有初始值及存在震荡
2) 在`noetic`branch下正确的Node Graph？`/gazebo`->`/wrench`是存在的么？我注意到[control_algorithms/admittance/launch/Admittance.launch](https://github.com/MingshanHe/Compliant-Control-and-Application/blob/a2627aaa78f7d4203475b63817d989a7ef0caa27/control_algorithms/admittance/launch/Admittance.launch)文件中：`<arg name="TOPIC_WRENCH_STATE" default="/wrench"/>`而不是使用`/wrench_fake`，不知道这里是否正确？
3) 以上两个branch的问题是否有一些提示呢？

感谢您的时间，期望您有空解答。Thanks!
Env: UBuntu 20 + Noetic, complied through `catkin build`

**Comment by MingshanHe** [comment]
1. 当时为了能够实现力位混合控制而采用了`ft_sensor`用来识别末端和物体的交互力，这个也可以通过GIF图片中看到，轮胎打磨需要指导末端与轮胎之间的交互力，从而采用该传感器。振荡的原因，主要是没有规定好数据发送的topic，因为传感器与代码都是对一个话题进行发布，导致了数据产生了波动。
2. noetic 分支是我在与实物进行调试的时候也会使用的代码，故将仿真与代码进行了整合，需要参考代码进行小部分修订。
3. 由于该项目停止开发好几个月，请原谅我无法为这两个分支提供更多的信息。如果日后有机会，我会进行代码重构，谢谢。

**Comment by YuHoChau** [comment]
非常感谢，期待您以后有机会update。

**Comment by YuHoChau** [comment]
您好，经过简单的修改后代码已能跑通，感谢帮助。但由于C++能力有限，还有两个小问题想请教：
1）`Wrench_Fake`生成的外力的单位是N么？2）笛卡尔速度控制中的反馈是？即`rqt_graph`中:

<img width="987" alt="Capture0" src="https://user-images.githubusercontent.com/63508270/197981416-f3525f6f-6fee-4a0c-b3b1-da5c4375a177.PNG">

由`/catesian_velocity_controller/ee_state`发送到`/Admittance`的是末端的速度和位置么，还是仅有位置？如果仅反馈位置的话，如果是实现拖动功能即`stiffness_parameter`为0，系统就失去了反馈？

<img width="970" alt="Capture1" src="https://user-images.githubusercontent.com/63508270/197980582-55febac7-7737-491e-96e1-af4cf37e1d7d.PNG">

感谢指正。

**Comment by MingshanHe** [comment]
1）力单位是N 2）控制器获取了机械臂的状态，通过正运动学获取末端位置与姿态 3）发送的是速度，`ros_control`底层拥有速度闭环，关节驱动模式为位置模式，故在底层中将速度积分至位置模式 4）反馈有速度与位置，故stiffness为0可以实现拖动，而不会失去反馈

**Comment by YuHoChau** [comment]
十分感谢！祝您生活愉快

**Comment by zhongzhuojian** [comment]
> 您好，经过简单的修改后代码已能跑通，感谢帮助。但由于C++能力有限，还有两个小问题想请教： 1）`Wrench_Fake`生成的外力的单位是N么？2）笛卡尔速度控制中的反馈是？即`rqt_graph`中:
> 
> <img alt="Capture0" width="987" src="https://user-images.githubusercontent.com/63508270/197981416-f3525f6f-6fee-4a0c-b3b1-da5c4375a177.PNG">
> 
> 由`/catesian_velocity_controller/ee_state`发送到`/Admittance`的是末端的速度和位置么，还是仅有位置？如果仅反馈位置的话，如果是实现拖动功能即`stiffness_parameter`为0，系统就失去了反馈？
> 
> <img alt="Capture1" width="970" src="https://user-images.githubusercontent.com/63508270/197980582-55febac7-7737-491e-96e1-af4cf37e1d7d.PNG">
> 
> 感谢指正。

请问您在此修改了什么

**Comment by YuHoChau** [comment]
你好，请参阅我基于本仓库作者修改后的repo: https://github.com/YuHoChau/UR_Admittance/tree/UR5e.
