### ISSUE TITLE
About Wrench_Fake.launch file

### ISSUE THREAD

**Issue by Eric120340** [MingshanHe/Compliant-Control-and-Application#16]
Hello, I have a problem about the **Wrench_Fake.launch** file, when I started the launch file, it says this. 
![image](https://user-images.githubusercontent.com/95627925/201005496-09ce6115-9c9c-4f5c-b2ca-4477bca7c82d.png)
Is this because I need to add information to the launch file by my own?

**Comment by MingshanHe** [comment]
I think this error occurs when you open a new terminal and run this command without sourcing your workspace. Please try to source your workspace before running this command.

**Comment by Eric120340** [comment]
Problem solved! thanks a lot. Have a good day
