### ISSUE TITLE
Could not load class 'cartesian_controller/CartesianVelocityController': Could not find library corresponding to plugin cartesian_controller/CartesianVelocityController. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.

### ISSUE THREAD

**Issue by zbj165** [MingshanHe/Compliant-Control-and-Application#23]
在运行roslaunch ur_gazebo ur5e_bringup.launch transmission_hw_interface:=hardware_interface/PositionJointInterface specified_controller:=cartesian_velocity_controller出现问题
![微信图片编辑_20230303164138](https://user-images.githubusercontent.com/109779867/222673234-65916a3e-5d90-4624-9cfb-6e844bc1ad61.jpg)

**Comment by MingshanHe** [comment]
由于cartesian_controller控制器编译加载失败导致，建议检查编译后的文件夹，以及编译过程的输出，检查是否成功编译该控制器并且写入build文件夹

**Comment by zbj165** [comment]
我是先把msg编译了下，再总的catkin-make。catkin_make中都没有报错，然后呢cartesian_controller这个我再build中搜索不到，我该去哪里再编译或者再编写过

**Comment by MingshanHe** [comment]
可以参考该[Link](https://answers.ros.org/question/54178/how-to-build-just-one-package-using-catkin_make/)，编译单独的控制器功能包，或者利用`catkin build`进行编译

**Comment by zbj165** [comment]
好了，我用catkin build重新编译了下行了，感谢

**Comment by daynad** [comment]
> 好了，我用catkin build重新编译了下行了，感谢

您好，请问您是在哪个文件夹下catkin build的，我的build文件夹里也没有cartesian_controller

**Comment by zbj165** [comment]
> > 好了，我用catkin build重新编译了下行了，感谢
> 
> 您好，请问您是在哪个文件夹下catkin build的，我的build文件夹里也没有cartesian_controller

我把build和dev文件都删了，初始化了下，好像是这么个流程catkin init
catkin build rm_msgs
catkin build
