### ISSUE TITLE
A problem was encountered while "catkin_make" in the workspace"catkin_ws"

### ISSUE THREAD

**Issue by daynad** [MingshanHe/Compliant-Control-and-Application#27]
In file included from /home/dayna/catkin_ws/src/Compliant-Control-and-Application-noetic/control_algorithms/admittance/src/HybridAdmittance/HybridAdmittance.cpp:1:
/home/dayna/catkin_ws/src/Compliant-Control-and-Application-noetic/control_algorithms/admittance/include/hybridadmittance/HybridAdmittance.h:6:10: fatal error: cartesian_state_msgs/PoseTwist.h: 没有那个文件或目录
    6 | #include "cartesian_state_msgs/PoseTwist.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/dayna/catkin_ws/src/Compliant-Control-and-Application-noetic/control_strategy/src/control_strategy/control_strategy.cpp:1:
/home/dayna/catkin_ws/src/Compliant-Control-and-Application-noetic/control_strategy/include/control_strategy/control_strategy.h:11:10: fatal error: cartesian_state_msgs/PoseTwist.h: 没有那个文件或目录
   11 | #include "cartesian_state_msgs/PoseTwist.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Compliant-Control-and-Application-noetic/control_algorithms/admittance/CMakeFiles/hybridadmittance.dir/build.make:63：Compliant-Control-and-Application-noetic/control_algorithms/admittance/CMakeFiles/hybridadmittance.dir/src/HybridAdmittance/HybridAdmittance.cpp.o] 错误 1
make[2]: *** [Compliant-Control-and-Application-noetic/control_strategy/CMakeFiles/control_strategy.dir/build.make:63：Compliant-Control-and-Application-noetic/control_strategy/CMakeFiles/control_strategy.dir/src/control_strategy/control_strategy.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:7219：Compliant-Control-and-Application-noetic/control_strategy/CMakeFiles/control_strategy.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/Makefile2:8657：Compliant-Control-and-Application-noetic/control_algorithms/admittance/CMakeFiles/hybridadmittance.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
Invoking "make -j2 -l2" failed
![image](https://user-images.githubusercontent.com/124642703/227765307-023106da-aa0f-4e8b-9e76-3a3b5ea573cd.png)

**Comment by MingshanHe** [comment]
Please refer this [answer](https://github.com/MingshanHe/Compliant-Control-and-Application/issues/6#issuecomment-1073596323)

**Comment by daynad** [comment]
> Please refer this [answer](https://github.com/MingshanHe/Compliant-Control-and-Application/issues/6#issuecomment-1073596323)

thanks!

**Comment by ZZWang21** [comment]
@daynad  did you solve this?
