### ISSUE TITLE
An error occurred when I ran the statement”roslaunch ur_gazebo ur5e_bringup.launch transmission_hw_interface:=hardware_interface/PositionJointInterface specified_controller:=cartesian_velocity_controller“

### ISSUE THREAD

**Issue by daynad** [MingshanHe/Compliant-Control-and-Application#28]
I ran this statement under the catkin_ws. The error is as follows：
![be63855073fd6c2729ad895e71f95bf](https://user-images.githubusercontent.com/124642703/227846880-f619571e-6206-4eda-9293-895eec4ccc13.png)
![ef29bf0d6b2ae3018beeb4e206a4bb5](https://user-images.githubusercontent.com/124642703/227846897-45ac4e79-0a6b-4afe-98be-04eaedfa2474.png)

**Comment by MingshanHe** [comment]
Actually, The first error you can ignore it. It won't make any sense.
The second error is the main one. You need to check if the self-defined controller has been compiled successfully in your project workspace.
