### ISSUE TITLE
roslaunch admittance Wrench_Fake.launch

### ISSUE THREAD

**Issue by zbj165** [MingshanHe/Compliant-Control-and-Application#32]
在运行roslaunch admittance Wrench_Fake.launch时，gazebo中机械臂不会继续动，命令行界面会卡在ROS_MASTER_URI=http://localhost:11311

process[WrenchSignalGenerate-1]: started with pid [51331]

**Comment by zbj165** [comment]
![微信图片_20230529181212](https://github.com/MingshanHe/Compliant-Control-and-Application/assets/109779867/30de828d-9cf3-404c-b7e2-a551dbf54bf7)

**Comment by MingshanHe** [comment]
这个问题从来没有遇到过，那个launch文件的运行就是为了代替在终端上向对应的话题发布外力，可以尝试对话题进行发布，并改写或自行写一个类似的功能的节点。

**Comment by zbj165** [comment]
![微信图片_20230530145107](https://github.com/MingshanHe/Compliant-Control-and-Application/assets/109779867/c15ce176-5d2b-49d4-a06b-30f4c1301bd1)
您好，我这样发布消息正确吗？还是没有动静

**Comment by zbj165** [comment]
![微信图片_20230531145224](https://github.com/MingshanHe/Compliant-Control-and-Application/assets/109779867/e4860736-6e75-435b-ab59-bfa48667e413)
您好，我发现该主题为被订阅，我该在哪订阅它

**Comment by liaoziyi0229** [comment]
@zbj165 您好，我在运行 Wrench_Fake.launch文件时遇到了同样的问题，您现在这个问题是否得到了解决？
我使用的ROS版本为melodic，这个问题是否与版本有关？

**Comment by zbj165** [comment]
> 您好，我在运行 Wrench_Fake.launchfile 时遇到了同样的问题，您现在这个问题是否得到了解决？ 我使用的ROS版本为旋律，这个问题是否与版本有关？

我用的是noetic版本，但应该不是与版本有关，这个话题没有被订阅，如我上面发的图所示，SUB那里为空。我目前还在看需要什么节点去订阅这个话题。

**Comment by liaoziyi0229** [comment]
@zbj165 您好，我尝试将订阅者修改为/gazebo，但是运行时仍显示SUB为空，并将ROS版本修改为noetic版本，也是同样的问题。您现在这个问题解决了吗？

**Comment by zbj165** [comment]
> @zbj165 您好，我尝试将订阅者修改为/gazebo，但是运行时仍显示SUB为空，并将ROS版本修改为noetic版本，也是同样的问题。您现在这个问题解决了吗？

按照逻辑来说应该将订阅者修改为/admittance ，但我改成/admittance后还是不会动。你可以参考这个[https://github.com/YuHoChau/UR_Admittance/tree/UR5e](url)

**Comment by MingshanHe** [comment]
明天我尝试维护一下

**Comment by MingshanHe** [comment]
我已经在仿真环境下维护了导纳控制，请尝试运行，谢谢对本项目的关注
I have update this repo, please test in your environment if it is possible
