### ISSUE TITLE
力位混合控制

### ISSUE THREAD

**Issue by NewFishNO1** [MingshanHe/Compliant-Control-and-Application#36]
作者您好，力位混合控制这部分是取消了吗？似乎目前的代码实现不了动图里的效果。感谢！

**Comment by MingshanHe** [comment]
由于当时一时兴起进行的短暂验证，经过长时间的代码删改，这部分代码将不再维护，谢谢！如若需要，可以按照写好的部分进行阅读并完善。

**Comment by NewFishNO1** [comment]
好的，感谢回复！
