### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by p1ckpep** [MingshanHe/Compliant-Control-and-Application#8]
-- Could not find the required component 'industrial_robot_status_interface'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "industrial_robot_status_interface" with any of the following names:

    industrial_robot_status_interfaceConfig.cmake
    industrial_robot_status_interface-config.cmake

**Comment by p1ckpep** [comment]
Compliant-Control-and-Application-main/universal_robot/Universal_Robots_ROS_Driver/ur_robot_driver/CMakeLists.txt:11 (find_package)

and my ubuntu version 18.04

**Comment by MingshanHe** [comment]
It needs some ros packages. I recommend you could search on Google or Baidu what makes this error happen.
I think you could run this command to avoid this error.
`sudo apt-get install ros-melodic-industrial-robot-status-interfaceConfig`
I hope you could search for something before opening the issue. Thanks a lot.

**Comment by p1ckpep** [comment]
Really appreciate that, i'll be more cautious. Thanks a lot!
